services:
  # 1. Spring Boot Application
  app:
    build: .
    container_name: shortudy-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shortudy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=wlalstn12
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JWT_SECRET=c2hvcnR1ZHktc2VjcmV0LWtleS1mb3ItZGV2ZWxvcG1lbnQtMjAyNjAxMTY=
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - shortudy-net

  # 2. MySQL Database
  db:
    image: mysql:8.0
    container_name: shortudy-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=shortudy
      - MYSQL_ROOT_PASSWORD=wlalstn12
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - shortudy-net

  # 3. Redis Cache
  redis:
    image: redis:alpine
    container_name: shortudy-redis
    ports:
      - "6379:6379"
    networks:
      - shortudy-net

networks:
  shortudy-net:
    driver: bridge

volumes:
  mysql-data:
