spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_lecture?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: gorilla
    password: gorilla
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY:lkqwhelkjhflkjhqawep123123h12kj3gk12jh3gk12jh3gk1j2h3gkjh12g3kjh}
  access-token-expiration: 180000 # 1시간 (밀리초 단위)
  refresh-token-expiration: 604800000 # 7일 (밀리초 단위)