name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main  # main 브랜치로 들어오는 PR만 감시

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Verify that the source branch is develop
        if: github.head_ref != 'develop'
        run: |
          echo "ERROR: Only 'develop' branch can be merged into 'main'."
          exit 1